version: '3.8'

services:
  crm360-backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/crm360
      - CLIENT_URL=http://localhost:5173
      - JWT_SECRET=production_secret_key_change_me
      - JWT_EXPIRE=1d
      - JWT_REFRESH_SECRET=production_refresh_secret_key_change_me
      - JWT_REFRESH_EXPIRE=7d
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
